services:
  server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: server_container
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://Isuru4043:Akalanka1999@cluster0.wb9vc.mongodb.net/ProShop?retryWrites=true&w=majority&appName=cluster0

  client:
    build: ./frontend
    container_name: client_container
    ports:
      - "3000:3000"
    depends_on:
      - server
    stdin_open: true
    tty: true
