services:
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"

  server:
    build: .
    container_name: server_container
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ProShop

  client:
    build: ./frontend
    container_name: client_container
    ports:
      - "3000:3000"
    depends_on:
      - server
    stdin_open: true
    tty: true
